spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
#mybatis:
#  mapperLocations: classpath:mapper/**/*.xml
#  configLocation: classpath:mybatis.xml

#mapper:
#  mappers:
#    - com.xuyun.platform.dsfcenterdao.mapper
#  style: normal
#  not-empty: false
#  identity: MYSQL

logging:
  config: classpath:logback-admin.xml


log:
  file: ./log/dsf-center-service.log

server:
  servlet:
    context-path: /dsf-center


