spring:
  application:
    name: invech-eureka-service
server:
  port: 7000

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
